import './globals.css';
import { cookies } from 'next/headers';
import Link from 'next/link';
import { getValidSessionById } from '../database/sessions';
import { getUserByIdInsecure } from '../database/users';
import { logout } from './(auth)/logout/actions';

// import localFont from 'next/font/local';

// const geistSans = localFont({
//   src: './fonts/GeistVF.woff',
//   variable: '--font-geist-sans',
//   weight: '100 900',
// });
// const geistMono = localFont({
//   src: './fonts/GeistMonoVF.woff',
//   variable: '--font-geist-mono',
//   weight: '100 900',
// });

export const metadata = {
  title: {
    default: 'Home | Poll App',
    template: '%s | Poll-App',
  },
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }) {
  const sessionCookie = cookies().get('sessionToken');
  const token =
    sessionCookie && (await getValidSessionById(sessionCookie.value));
  const userId = token?.userId;
  let user = null;

  if (userId !== undefined) {
    user = await getUserByIdInsecure(userId);
  }
  return (
    <html lang="en">
      <body>
        <header>
          <nav className="main-nav">
            <div className="left-nav">
              <Link href="/">Home</Link>
            </div>
            <div className="right-nav">
              <div className="signIn">
                {user ? (
                  <form action={logout} method="post">
                    <button className="auth-button logout-button">
                      Logout
                    </button>
                  </form>
                ) : (
                  <Link href="/login" className="auth-button">Sign In</Link>
                )}
              </div>
              <details className="dropdown">
                <summary className="dropdown-summary">Menu</summary>
                <div className="dropdown-content">
                  <Link href="/register">Sign Up</Link>
                  <Link href="/createPolls">Polls</Link>
                  <Link href={`/profile/${user?.userName}`}>Profile</Link>
                </div>
              </details>
            </div>
          </nav>
        </header>
        <main>{children}</main>
      </body>
    </html>
  );
}

/* <body className={`${geistSans.variable} ${geistMono.variable}`}> */
