import { cookies } from 'next/headers';
import Link from 'next/link';
import { redirect } from 'next/navigation';
import { getAllPollsInsecure, Poll } from '../../database/polls';
import { getValidSession } from '../../database/sessions';
import styles from './Dashboard.module.scss';

export const metadata = {
  title: 'Poll Admin page',
  description: 'Generated by create next app',
};

export default async function PollsPage() {
  // Task: Protect the dashboard page and redirect to login if the user is not logged in
  // 1. Checking if the sessionToken cookie exists
  const sessionCookie = cookies().get('sessionToken');

  // 2. Check if the sessionToken cookie is still valid
  const session = sessionCookie && (await getValidSession(sessionCookie.value));

  // 3. If the sessionToken cookie is invalid or doesn't exist, redirect to login with returnTo
  if (!session) {
    redirect(`/login?returnTo=/dashboard`); // once you set up the polls folder this must look like that: redirect(`/login?returnTo=/polls/dashboard`)
  }

  // const polls = await getPolls(session.token)  --> for this you also need to change the sessions.ts file as mentioned below and explained in the video session:review

  // 4. Fetch all polls from the database
  const polls: Poll[] = await getAllPollsInsecure();

  return (
    <div className={styles.dashboardContainer}>
      <h1>Dashboard</h1>
      <h2>All Polls</h2>
      <ul className={styles.pollsList}>
        {polls.map((poll) => (
          <li key={`poll-${poll.id}`} className={styles.pollCard}>
            <Link href={`/poll/${poll.id}`}>
              <div className={styles.pollCardContent}>
                <h3 className={styles.pollCardTitle}>{poll.title}</h3>
                <p className={styles.pollCardText}>{poll.description}</p>
              </div>
            </Link>
          </li>
        ))}
      </ul>
    </div>
  );

  // 4. If the sessionToken cookie is valid, allow access to dashboard page
  // return <PollsForm polls={polls} />;

  // check out video Sessions: Review.... Minute 9. He also changes sessions.ts file getValidSession. you will also need to create the getPolls function in the polls.ts file in /database that is not yet created. all in the video
}
